### ISSUE TITLE
Latest broken in 1.14

### ISSUE THREAD

**Issue by supertassu** [iso2013/PacketEntityAPI#5]
* Steps to reproduce
1. Create a 1.14 server
2. Add PacketEntityAPI
3. Start server

* Expected behaviour
Server starts properly

* Actual outcome
```
[13:31:57 ERROR]: Could not load 'plugins/PacketEntityAPI-0.7.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchFieldError: TIPPED_ARROW
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.jar:git-Paper-9]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336) ~[patched_1.14.jar:git-Paper-9]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) ~[patched_1.14.jar:git-Paper-9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:352) ~[patched_1.14.jar:git-Paper-9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:216) ~[patched_1.14.jar:git-Paper-9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.14.jar:git-Paper-9]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchFieldError: TIPPED_ARROW
        at net.blitzcube.peapi.PacketEntityAPI.<clinit>(PacketEntityAPI.java:56) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.jar:git-Paper-9]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.jar:git-Paper-9]
        ... 6 more
```

* Minecraft version *(Only 1.13 is officially supported)*
```
This server is running Paper version git-Paper-9 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
```

* Plugin list
```
Plugins (8): Citizens, FeatherBoard*, Fjurt*, LuckPerms, MVdWPlaceholderAPI*, ProtocolLib*, Vault, VaultChatFormatter*
```

**Comment by iso2013** [comment]
1.14 is currently not supported.

1.14 is in progress; however. I had to wait for a ProtocolLib 1.14 beta to arrive first.

**Comment by supertassu** [comment]
Hi!

Any updates? I tried to fix it myself but failed as I'm not too familiar with packets.

**Comment by iso2013** [comment]
There still isn't any working ProtocolLib 1.14, as far as I'm aware. At least not one that has javadocs.

I'm waiting until I have time to reverse engineer ProtocolLib and implement its functionality directly into PacketEntityAPI. This will remove the dependency allowing faster updates and easier implementation.

**Comment by iso2013** [comment]
Help wanted: https://www.spigotmc.org/threads/synchronous-packet-listening-creation-modification.384840/

**Comment by frostalf** [comment]
Should be resolved now.
